### default supported ROS message types:
# sensor_msgs/Imu
# geometry_msgs/Twist
# std_msgs/String
# (modify/add in ros_sub_pub.hpp if you need more)
### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: '*'   # '*' stands for all self IPs
  joint: 192.168.137.10
  sensor: 192.168.137.112
  test_local: 127.0.0.1 # just for local machine test

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
send_topics:
- topic_name: /imu_state # send the messages of this ROS topic
  msg_type: sensor_msgs/Imu # ROS message type (rosmsg style)
  max_freq: 1000 # max sending frequency (Hz) int
  srcIP: self # self IP
  srcPort: 3001 # ports of send_topics should be different

- topic_name: /cmd_vel # send the messages of this ROS topic
  msg_type: geometry_msgs/Twist # ROS message type (rosmsg style)
  max_freq: 50 # max sending frequency (Hz) int
  srcIP: self # self IP
  srcPort: 3002 # ports of send_topics should be different

- topic_name: /string # send the messages of this ROS topic
  msg_type: std_msgs/String # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: self # self IP
  srcPort: 3003 # ports of send_topics should be different

- topic_name: /cmd_lida # send the messages of this ROS topic
  msg_type: fd_exoskeleton/CmdMessage # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: self # self IP
  srcPort: 3004 # ports of send_topics should be different

- topic_name: /cmd_imu # send the messages of this ROS topic
  msg_type: fd_exoskeleton/CmdMessage # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: self # self IP
  srcPort: 3005 # ports of send_topics should be different

- topic_name: /JointState # send the messages of this ROS topic
  msg_type: sensor_msgs/JointState # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: self # self IP
  srcPort: 3006 # ports of send_topics should be different

- topic_name: /exo_humanoid_gazebo/L_hip_controller/command # send the messages of this ROS topic
  msg_type: unitree_legged_msgs/MotorCmd # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: self #  message source IPname
  srcPort: 3007 # ports of send_topics should be different

- topic_name: /exo_humanoid_gazebo/L_hip2_controller/command # send the messages of this ROS topic
  msg_type: unitree_legged_msgs/MotorCmd # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: self #  message source IPname
  srcPort: 3008 # ports of send_topics should be different

- topic_name: /exo_humanoid_gazebo/L_calf_controller/command # send the messages of this ROS topic
  msg_type: unitree_legged_msgs/MotorCmd # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: self #  message source IPname
  srcPort: 3010 # ports of send_topics should be different

- topic_name: /exo_humanoid_gazebo/L_toe_controller/command # send the messages of this ROS topic
  msg_type: unitree_legged_msgs/MotorCmd # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: self #  message source IPname
  srcPort: 3011 # ports of send_topics should be different

 
- topic_name: /exo_humanoid_gazebo/R_hip_controller/command # send the messages of this ROS topic
  msg_type: unitree_legged_msgs/MotorCmd # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: self #  message source IPname
  srcPort: 3012 # ports of send_topics should be different

- topic_name: /exo_humanoid_gazebo/R_hip2_controller/command # send the messages of this ROS topic
  msg_type: unitree_legged_msgs/MotorCmd # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: self #  message source IPname
  srcPort: 3013 # ports of send_topics should be different

- topic_name: /exo_humanoid_gazebo/R_calf_controller/command # send the messages of this ROS topic
  msg_type: unitree_legged_msgs/MotorCmd # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: self #  message source IPname
  srcPort: 3014 # ports of send_topics should be different

- topic_name: /exo_humanoid_gazebo/R_toe_controller/command # send the messages of this ROS topic
  msg_type: unitree_legged_msgs/MotorCmd # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: self #  message source IPname
  srcPort: 3015 # ports of send_topics should be different


####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
- topic_name: /gazebo/imu_state # the received messages will be published in this topic
  msg_type: sensor_msgs/Imu # ROS message type (rosmsg style)
  srcIP: sensor # message source IPname
  srcPort: 3001 # message source port

- topic_name: /cmd_vel_recv # the received messages will be published in this topic
  msg_type: geometry_msgs/Twist # ROS message type (rosmsg style)
  srcIP: sensor # message source IPname
  srcPort: 3002 # message source port

- topic_name: /string_recv # the received messages will be published in this topic
  msg_type: std_msgs/String # ROS message type (rosmsg style)
  srcIP: sensor # message source IPname
  srcPort: 3003 # message source port


- topic_name: /cmd_lida_recv # send the messages of this ROS topic
  msg_type: fd_exoskeleton/CmdMessage # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: sensor # self IP
  srcPort: 3004 # ports of send_topics should be different

- topic_name: /cmd_imu_recv # send the messages of this ROS topic
  msg_type: fd_exoskeleton/CmdMessage # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: sensor # self IP
  srcPort: 3005 # ports of send_topics should be different

- topic_name: /JointState_recv # send the messages of this ROS topic
  msg_type: sensor_msgs/JointState # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: joint # self IP
  srcPort: 3006 # ports of send_topics should be different

- topic_name: /exo_humanoid_gazebo/L_hip_controller/state # send the messages of this ROS topic
  msg_type: unitree_legged_msgs/MotorState # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: joint #  message source IPname
  srcPort: 3007 # ports of send_topics should be different

- topic_name: /exo_humanoid_gazebo/L_hip2_controller/state # send the messages of this ROS topic
  msg_type: unitree_legged_msgs/MotorState # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: joint #  message source IPname
  srcPort: 3008 # ports of send_topics should be different

- topic_name: /exo_humanoid_gazebo/L_calf_controller/state # send the messages of this ROS topic
  msg_type: unitree_legged_msgs/MotorState # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: joint #  message source IPname
  srcPort: 3010 # ports of send_topics should be different

- topic_name: /exo_humanoid_gazebo/L_toe_controller/state # send the messages of this ROS topic
  msg_type: unitree_legged_msgs/MotorState # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: joint #  message source IPname
  srcPort: 3011 # ports of send_topics should be different


- topic_name: /exo_humanoid_gazebo/R_hip_controller/state # send the messages of this ROS topic
  msg_type: unitree_legged_msgs/MotorState # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: joint #  message source IPname
  srcPort: 3012 # ports of send_topics should be different

- topic_name: /exo_humanoid_gazebo/R_hip2_controller/state # send the messages of this ROS topic
  msg_type: unitree_legged_msgs/MotorState # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: joint #  message source IPname
  srcPort: 3013 # ports of send_topics should be different

- topic_name: /exo_humanoid_gazebo/R_calf_controller/state # send the messages of this ROS topic
  msg_type: unitree_legged_msgs/MotorState # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: joint #  message source IPname
  srcPort: 3014 # ports of send_topics should be different

- topic_name: /exo_humanoid_gazebo/R_toe_controller/state # send the messages of this ROS topic
  msg_type: unitree_legged_msgs/MotorState # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: joint #  message source IPname
  srcPort: 3015 # ports of send_topics should be different